const ADD_TASK = "ADD_TASK";
const GET_TASK_LIST = "GET_TASK_LIST";
const PATCH_TASK = "PATCH_TASK";
const UPDATE_CHOSEN_TASK = "UPDATE_CHOSEN_TASK";
const SET_EDITING_TASK_MODE = "SET_EDITING_TASK_MODE ";
const SET_NEW_CATEGORY_FOR_TASK = "SET_NEW_CATEGORY_FOR_TASK";
const SET_IS_SEARCH = "SET_IS_SEARCH";
const SET_SEARCH_CRITERIA = "SET_SEARCH_CRITERIA";

module.exports = {
  ADD_TASK,
  GET_TASK_LIST,
  PATCH_TASK,
  UPDATE_CHOSEN_TASK,
  SET_EDITING_TASK_MODE,
  SET_NEW_CATEGORY_FOR_TASK,
  SET_IS_SEARCH,
  SET_SEARCH_CRITERIA,
};
